# Need sudo permissions
sudo: required
services:
  - docker

before_install:
  # Don't NEED to put username/project-name, can just be "test" etc, but good convention
  - docker build -t alistairreynolds/docker-react -f Dockerfile.dev .

script:
  # Need -- --coverage as a workaround so it can auto-exit after the test instead of waiting for input
  - docker run -e CI=true alistairreynolds/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-west-2-529160058515"
  bucket_path: "docker-react" # Same as the app name to before deploying
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY